make:
	java HW4 0 monks-train0.txt monks-tune0.txt monks-test0.txt 
	java HW4 1 monks-train0.txt monks-tune0.txt monks-test0.txt 
	java HW4 2 monks-train0.txt monks-tune0.txt monks-test0.txt
	java HW4 3 monks-train0.txt monks-tune0.txt monks-test0.txt
	java HW4 4 monks-train0.txt monks-tune0.txt monks-test0.txt

#	java HW4 0 monks-train2.txt monks-tune2.txt monks-test2.txt 
#	java HW4 1 monks-train2.txt monks-tune2.txt monks-test2.txt 
#	java HW4 2 monks-train2.txt monks-tune2.txt monks-test2.txt
#	java HW4 3 monks-train2.txt monks-tune2.txt monks-test2.txt
#	java HW4 4 monks-train2.txt monks-tune2.txt monks-test2.txt

